version: '3'

services:

  account-scs:
    image: account-scs
    container_name: account-scs
    env_file: account-scs/.env

  home-scs:
    image: home-scs
    container_name: home-scs
    env_file: home-scs/.env

  items-mongodb:
    image: mongo:3
    container_name: items-mongodb

  items-scs:
    image: items-scs
    container_name: items-scs
    depends_on:
      - items-mongodb
    environment:
      - DATABASE_URL=mongodb://items-mongodb:27017
    env_file: items-scs/.env

  scs-proxy:
    image: scs
    build:
      context: .
    container_name: scs
    ports:
      - "$NGINX_PORT:$NGINX_PORT"
    depends_on:
      - home-scs
      - account-scs
      - items-scs
    env_file: .env
